config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  resources :pokemons
  resources :offers
  resources :desired_pokemons
  resources :owned_pokemons
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/desired_pokemon.rb
class DesiredPokemon < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon

  def species
    pokemon.species
  end
end

app/controllers/desired_pokemons_controller.rb
class DesiredPokemonsController < ApplicationController
  before_action :set_desired_pokemon, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:index]
  skip_before_action :verify_authenticity_token, :only => [:create, :destroy]

  # GET /desired_pokemons
  # GET /desired_pokemons.json
  def index
    @desired_pokemons = current_user.desired_pokemons
  end

  # GET /desired_pokemons/1
  # GET /desired_pokemons/1.json
  def show
  end

  # GET /desired_pokemons/new
  def new
    @desired_pokemon = DesiredPokemon.new
  end

  # GET /desired_pokemons/1/edit
  def edit
  end

  # POST /desired_pokemons
  # POST /desired_pokemons.json
  def create
    puts 'It is in create'
    puts "params #{desired_pokemon_params}"
    
    parameters = desired_pokemon_params.merge!(user_id: current_user.id)

    @desired_pokemon = DesiredPokemon.new(parameters)

    respond_to do |format|
      if @desired_pokemon.save
        format.html { redirect_to @desired_pokemon, notice: 'Desired pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @desired_pokemon }
      else
        format.html { render :new }
        format.json { render json: @desired_pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desired_pokemons/1
  # PATCH/PUT /desired_pokemons/1.json
  def update
    respond_to do |format|
      if @desired_pokemon.update(desired_pokemon_params)
        format.html { redirect_to @desired_pokemon, notice: 'Desired pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @desired_pokemon }
      else
        format.html { render :edit }
        format.json { render json: @desired_pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desired_pokemons/1
  # DELETE /desired_pokemons/1.json
  def destroy
    @desired_pokemon.destroy
    respond_to do |format|
      format.html { redirect_to desired_pokemons_url, notice: 'Desired pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desired_pokemon
      @desired_pokemon = DesiredPokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def desired_pokemon_params
      params.require(:desired_pokemon).permit(:user_id, :pokemon_id, :min_cp)
    end
end

app/helpers/desired_pokemons_helper.rb
module DesiredPokemonsHelper
end

app/views/desired_pokemons/_form.html.erb
<%= form_with(model: desired_pokemon, local: true) do |form| %>
  <% if desired_pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(desired_pokemon.errors.count, "error") %> prohibited this desired_pokemon from being saved:</h2>

      <ul>
      <% desired_pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :desired_pokemon_user_id %>
  </div>

  <div class="field">
    <%= form.label :pokemon_id %>
    <%= form.number_field :pokemon_id, id: :desired_pokemon_pokemon_id %>
  </div>

  <div class="field">
    <%= form.label :min_cp %>
    <%= form.number_field :min_cp, id: :desired_pokemon_min_cp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/desired_pokemons/edit.html.erb
<h1>Editing Desired Pokemon</h1>

<%= render 'form', desired_pokemon: @desired_pokemon %>

<%= link_to 'Show', @desired_pokemon %> |
<%= link_to 'Back', desired_pokemons_path %>

app/views/desired_pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Desired Pokemons</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Pokemon</th>
      <th>Min cp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @desired_pokemons.each do |desired_pokemon| %>
      <tr>
        <td><%= desired_pokemon.user_id %></td>
        <td><%= desired_pokemon.pokemon_id %></td>
        <td><%= desired_pokemon.min_cp %></td>
        <td><%= link_to 'Show', desired_pokemon %></td>
        <td><%= link_to 'Edit', edit_desired_pokemon_path(desired_pokemon) %></td>
        <td><%= link_to 'Destroy', desired_pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Desired Pokemon', new_desired_pokemon_path %>

app/views/desired_pokemons/new.html.erb
<h1>New Desired Pokemon</h1>

<%= render 'form', desired_pokemon: @desired_pokemon %>

<%= link_to 'Back', desired_pokemons_path %>

app/views/desired_pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @desired_pokemon.user_id %>
</p>

<p>
  <strong>Pokemon:</strong>
  <%= @desired_pokemon.pokemon_id %>
</p>

<p>
  <strong>Min cp:</strong>
  <%= @desired_pokemon.min_cp %>
</p>

<%= link_to 'Edit', edit_desired_pokemon_path(@desired_pokemon) %> |
<%= link_to 'Back', desired_pokemons_path %>