config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  resources :pokemons
  resources :offers
  resources :desired_pokemons
  resources :owned_pokemons
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :offered_pokemons
  has_many :owned_pokemons, :through => :offered_pokemons

  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, :only => [:create]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
    
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    offer_params = params

    @offer = Offer.new({status: offer_params[:status]})
    offer_save = @offer.save

    if offer_save
      p offer_params['owned_pokemon_id_1']

      @offered_pokemon_1 = OfferedPokemon.new({
        offer_id: @offer.id,
        owned_pokemon_id: offer_params['owned_pokemon_id_1'],
      })
      offered_pokemon_1_save = @offered_pokemon_1.save

      p offer_params['owned_pokemon_id_2']
      @offered_pokemon_2 = OfferedPokemon.new({
        offer_id: @offer.id,
        owned_pokemon_id: offer_params['owned_pokemon_id_2'],
      })
      offered_pokemon_2_save = @offered_pokemon_2.save

    end
    
    # respond_to do |format|
      if  offer_save && offered_pokemon_1_save && offered_pokemon_2_save
        # format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        # format.json { render :show, status: :created, location: @offer }
        render json: @offer
      else
        puts "#{@offer.save} && #{@offered_pokemon_1.save} && #{@offered_pokemon_2.save}"
        # format.html { render :new }
        # format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    # end

  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      # params.require(:offer).permit(:owned_pokemon_id_1, :owned_pokemon_id_2, :status, :format, :offer)
      params.permit(:owned_pokemon_id_1, :owned_pokemon_id_2, :status, :format, :offer)
      # params.permit(:owned_pokemon_id_1, :owned_pokemon_id_2, :status, :format)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_with(model: offer, local: true) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :owned_pokemon_id_1 %>
    <%= form.number_field :owned_pokemon_id_1, id: :offer_owned_pokemon_id_1 %>
  </div>

  <div class="field">
    <%= form.label :owned_pokemon_id_2 %>
    <%= form.number_field :owned_pokemon_id_2, id: :offer_owned_pokemon_id_2 %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, id: :offer_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <th>Owned pokemon id 1</th>
      <th>Owned pokemon id 2</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.owned_pokemon_id_1 %></td>
        <td><%= offer.owned_pokemon_id_2 %></td>
        <td><%= offer.status %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owned pokemon id 1:</strong>
  <%= @offer.owned_pokemon_id_1 %>
</p>

<p>
  <strong>Owned pokemon id 2:</strong>
  <%= @offer.owned_pokemon_id_2 %>
</p>

<p>
  <strong>Status:</strong>
  <%= @offer.status %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>