config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  resources :pokemons
  resources :offers
  resources :desired_pokemons
  resources :owned_pokemons
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/owned_pokemon.rb
class OwnedPokemon < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
  has_many :offered_pokemons
  has_many :offers, :through => :offered_pokemons

  def species
    pokemon.species
  end
end

app/controllers/owned_pokemons_controller.rb
class OwnedPokemonsController < ApplicationController
  before_action :set_owned_pokemon, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:index]
  skip_before_action :verify_authenticity_token, :only => [:create, :destroy]

  # GET /owned_pokemons
  # GET /owned_pokemons.json
  def index
    @owned_pokemons = current_user.owned_pokemons
  end

  # GET /owned_pokemons/1
  # GET /owned_pokemons/1.json
  def show
    puts params
    offers = OwnedPokemon.find(params[:id].to_i).offers
    # offers = offered_pokemons.map { |offered_pokemon| Offer.find(offered_pokemon.offer_id) }
    # @owned_pokemons = offers.map { |offer| OwnedPokemon.find(offered_pokemon.offer_id) }
   
    offered_pokemons = offers.map { |offer| OfferedPokemon.all.where({offer_id: offer.id.to_i}) }
   
    filtered_offered_pokemons = offered_pokemons.flatten.select{|offered_pokemon| offered_pokemon[:owned_pokemon_id].to_i != params[:id].to_i}
   
    @owned_pokemons = filtered_offered_pokemons.map { |offered_pokemon|  OwnedPokemon.find(offered_pokemon[:owned_pokemon_id].to_i) }

    render 'index.json.jbuilder'
  end

  # GET /owned_pokemons/new
  def new
    @owned_pokemon = OwnedPokemon.new
  end

  # GET /owned_pokemons/1/edit
  def edit
  end

  # POST /owned_pokemons
  # POST /owned_pokemons.json
  def create
    puts 'It is in create'
    puts "params #{owned_pokemon_params}"
    # parameters = owned_pokemon_params
    parameters = owned_pokemon_params.merge!(user_id: current_user.id)
    puts "params v2 #{parameters}"
    @owned_pokemon = OwnedPokemon.new(parameters)

    respond_to do |format|
      if @owned_pokemon.save
        format.html { redirect_to @owned_pokemon, notice: 'Owned pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @owned_pokemon }
      else
        format.html { render :new }
        format.json { render json: @owned_pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owned_pokemons/1
  # PATCH/PUT /owned_pokemons/1.json
  def update
    respond_to do |format|
      if @owned_pokemon.update(owned_pokemon_params)
        format.html { redirect_to @owned_pokemon, notice: 'Owned pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @owned_pokemon }
      else
        format.html { render :edit }
        format.json { render json: @owned_pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owned_pokemons/1
  # DELETE /owned_pokemons/1.json
  def destroy
    @owned_pokemon.destroy
    respond_to do |format|
      format.html { redirect_to owned_pokemons_url, notice: 'Owned pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owned_pokemon
      @owned_pokemon = OwnedPokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owned_pokemon_params
      params.require(:owned_pokemon).permit(:user_id, :nickname, :combat_power, :pokemon_id)
    end
end

app/helpers/owned_pokemons_helper.rb
module OwnedPokemonsHelper
end

app/views/owned_pokemons/_form.html.erb
<%= form_with(model: owned_pokemon, local: true) do |form| %>
  <% if owned_pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(owned_pokemon.errors.count, "error") %> prohibited this owned_pokemon from being saved:</h2>

      <ul>
      <% owned_pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :owned_pokemon_user_id %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, id: :owned_pokemon_nickname %>
  </div>

  <div class="field">
    <%= form.label :combat_power %>
    <%= form.number_field :combat_power, id: :owned_pokemon_combat_power %>
  </div>

  <div class="field">
    <%= form.label :pokemon_id %>
    <%= form.number_field :pokemon_id, id: :owned_pokemon_pokemon_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/owned_pokemons/edit.html.erb
<h1>Editing Owned Pokemon</h1>

<%= render 'form', owned_pokemon: @owned_pokemon %>

<%= link_to 'Show', @owned_pokemon %> |
<%= link_to 'Back', owned_pokemons_path %>

app/views/owned_pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Owned Pokemons</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Nickname</th>
      <th>Combat power</th>
      <th>Pokemon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owned_pokemons.each do |owned_pokemon| %>
      <tr>
        <td><%= owned_pokemon.user_id %></td>
        <td><%= owned_pokemon.nickname %></td>
        <td><%= owned_pokemon.combat_power %></td>
        <td><%= owned_pokemon.pokemon_id %></td>
        <td><%= link_to 'Show', owned_pokemon %></td>
        <td><%= link_to 'Edit', edit_owned_pokemon_path(owned_pokemon) %></td>
        <td><%= link_to 'Destroy', owned_pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owned Pokemon', new_owned_pokemon_path %>

app/views/owned_pokemons/new.html.erb
<h1>New Owned Pokemon</h1>

<%= render 'form', owned_pokemon: @owned_pokemon %>

<%= link_to 'Back', owned_pokemons_path %>

app/views/owned_pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @owned_pokemon.user_id %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @owned_pokemon.nickname %>
</p>

<p>
  <strong>Combat power:</strong>
  <%= @owned_pokemon.combat_power %>
</p>

<p>
  <strong>Pokemon:</strong>
  <%= @owned_pokemon.pokemon_id %>
</p>

<%= link_to 'Edit', edit_owned_pokemon_path(@owned_pokemon) %> |
<%= link_to 'Back', owned_pokemons_path %>